{
 "title": "API Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tykapiname", "label": "API", "query": { "query": "label_values(tyk_api_name)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<h3>API Observability</h3>\npowered by<br /> \nTyk & OpenTelemetry<br />\n\n<img width= \"170\" src=\"/public/img/tyk-opentelemetry.png\" />\n<br />\n🔗 <a href=\"http://localhost:16686/\" target=\"_blank\">Distributed traces in Jaeger</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 6, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])) or vector(0)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(calls_total{span_kind=\"SPAN_KIND_SERVER\",http_status_code=~\"[5][0-9]{2}\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])) or vector(0)\n\n",
     "legendFormat": "Server-side errors"
    },
    {
     "expr": "sum(rate(calls_total{span_kind=\"SPAN_KIND_SERVER\",http_status_code=~\"[4][0-9]{2}\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])) or vector(0)\n\n",
     "legendFormat": "Client-side errors"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])) by (le)) or vector(0)",
     "legendFormat": "Duration (p99)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests by response code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (\n  rate(calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by http method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_method) (\n  rate(calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "p99, p95, p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\"}[1m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Duration per span name",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}[1m])) by (le, span_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}) by (tyk_gw_id))\n",
     "legendFormat": "Number of API gateways"
    }
   ]
  },
  {
   "title": "Requests by API gateway",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (tyk_gw_id) (\n  rate(calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\", service_name=\"tyk_gateway\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk_gateway\"}) by (service_version))\n",
     "legendFormat": "API gateway versions"
    }
   ]
  },
  {
   "title": "Requests by API gateway version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_version) (\n  rate(calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\", service_name=\"tyk_gateway\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}