global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
- job_name: tyk-gateway
  static_configs:
  - targets:
    - 'otel-collector:9464'
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otel-collector:8888'